USE mysns;

ALTER TABLE user
ADD COLUMN bio VARCHAR(512);

ALTER TABLE user
ADD COLUMN profile_image VARCHAR(1024);

ALTER TABLE feed
ADD COLUMN title VARCHAR(128);

CREATE TABLE IF NOT EXISTS reply(
    no INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    feed_no INT UNSIGNED,
    id VARCHAR(128),
    content VARCHAR(1024),
    ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS feed_like(
    feed_no INT UNSIGNED,
    id VARCHAR(128),
    ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(feed_no, id)
);

CREATE TABLE IF NOT EXISTS follow(
    follower_id VARCHAR(128),
    target_id VARCHAR(128),
    ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(follower_id, target_id)
);

UPDATE feed
SET title = '제목 없음'
WHERE title IS NULL OR title = '';
